#cloud-config
timezone: Europe/Oslo
users:
  - name: ansible_user
    passwd: $6$rounds=4096$nS48C7JOJTViAzUE$2956KAOhX4b0Qbb6gIsCx20bGKmsnuvWQ4ByaONumP3HAzwwgsxlhU78RyD6QDugth8pTeZbRMo6Z70YiCCHH1
    groups: [adm, cdrom, dip, plugdev, lxd, sudo]
    lock-passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDLFvndqnOOzZfZdxU9gjhwjwVD/3C24hAMVQeOFMNRctg1UJgAWaF2c924tPdXY2REYqR/ZBjJl+TAuT8mkYoqBxtaFOfpi5xyp5aPVLa3kTX/7WGJM+2lRzrTpliS/kSZbSm2L7ZnGtBXK7y5omPHsaVt1KkIEiP/6Yj24LI5hQR0xVZZ6po5BXgkIc9X9oUFJT6+2baBAlcGx5w7QqshlkeF5oteOseqLgs2d6l9+fbeDK1d8u/ObMOOOBn+pY7hw73xQh4mxBXJX//LSiAppGrxi7QtKd0h4V60uNdtPk+MqZmwYp9cIKQzRUmnsi7YAugknaLvuSXPq48Kt+OxH6F91SL9Dv4a/fwNcXJSvHLlCh5a7yrd4J1deV9a4RX9aR0LPxAds7Vk/BbsDL2qjre4Y8HqTGXi/TV+VgkARTIVqxwjYkbQ+vjhocuZ9ycoW4d173JB6umjIXivHInmUg1T+IkoYhZjn1DKaCJVpD0jbiS4RRqLEc2B8E6nzPkqpgn01NFgM3ETo37M4ga0r3pu3HB2E6AEmgboaeqO0/T1yREFrNeiqrTq9/QeKVqH8HkxIldXQg2n2R7qgdlT6SSbpf4aQysI+IrQBZyUH0Ln82OMhXP9wZqsOv7nJ1PRzjkyLjL//qhAsQkq8IEE7NS3elmdUyEnWbsGJl3uWw== workstation"
#  - name: root
#    lock_passwd: false
#    passwd: $6$rounds=4096$nS48C7JOJTViAzUE$2956KAOhX4b0Qbb6gIsCx20bGKmsnuvWQ4ByaONumP3HAzwwgsxlhU78RyD6QDugth8pTeZbRMo6Z70YiCCHH1
#    #hashed_passwd: <output from mkpasswd --method=SHA-512 --rounds=4096>
#    ssh_authorized_keys:
#      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCr9kjW6uU2txnlQuA4fJR7iMEMHoDl/S0DNZKXMmnLVRu+YvM08UD9R+XJK8W/6FxNt/MnJkuRgELxPj6SRb3VUOuRgAxvKY6fEK4bE3Jh8VSprCGp60ud2JhUR3kput9ixkSZWeRCrEv/EEFVu6ylv+vR+HIYWrLPwldIvZyaaxiCcLldtu0xp+NUswpQcI/HgNZCIV5lWLO3mVHx3E7D7lNcFTwty0qVQ5EssC4gNdPXOd8fbY1UGLYq+yknguJ3+H1Dj74MxKlSzMR4bZUVxoIJNVwF1Yb7ICfOo6BzKeG/0XXeqc8kk6WvJyTokQryb9Dn3EX2kplRxutaKODBlvklUc4w10D6VIZ8dW3Fnupu41KT5xb+N4l8xS6pbCY3wDeraUyWMAsCSkuofbjpLGapB42kLLv58qjcZlEfM85j9XCtov/bKHKjY+4JvLqLyMa5zKNj0yMilzHkKUuVyQABPETq80+G7CXVlOobOL8dAFcJ/TxfKxTe4CxKZTXwVoJFla1rHSkNjjY8uAwuS1ik4wlxXpGgX3fcVsK4iP2aNhv2RfcCY+5vMNUMnlphfWcxrQbQXoMCBDB9oKjXMcZ/LRJrr4rOeTALGSRACz+SD7KaoQEi/yCDtXzygb9GqykDamAETEHqhxc1kq5kuvQmGBSxNTz45Qrq/p9c5Q== workstation"

runcmd:
# Install GitHub Actions Runner
  - apt update
  - apt install -y qemu-guest-agent

power_state:
    delay: now
    mode: reboot
    message: Rebooting after cloud-init completion
    condition: true