#cloud-config
timezone: Europe/Oslo
users:
  - name: ansible_user
    hashed_passwd: $6$rounds=4096$nS48C7JOJTViAzUE$2956KAOhX4b0Qbb6gIsCx20bGKmsnuvWQ4ByaONumP3HAzwwgsxlhU78RyD6QDugth8pTeZbRMo6Z70YiCCHH1
    groups: [adm, cdrom, dip, plugdev, lxd, sudo]
    lock-passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC9/VPpPfpTVgNmiFXPWZfpYRwao5lsu1S06WeKwIskl root@HauPC"
  - name: root
    lock_passwd: false
    hashed_passwd: $6$rounds=4096$nS48C7JOJTViAzUE$2956KAOhX4b0Qbb6gIsCx20bGKmsnuvWQ4ByaONumP3HAzwwgsxlhU78RyD6QDugth8pTeZbRMo6Z70YiCCHH1
    #hashed_passwd: <output from mkpasswd --method=SHA-512 --rounds=4096>
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC9/VPpPfpTVgNmiFXPWZfpYRwao5lsu1S06WeKwIskl root@HauPC"

runcmd:
# Install GitHub Actions Runner
  - apt update && apt upgrade -y
  - apt install -y qemu-guest-agent

power_state:
    delay: now
    mode: reboot
    message: Rebooting after cloud-init completion
    condition: true