- name: Install Keepalived
  ansible.builtin.apt:
    name: keepalived
    state: present
    update_cache: true

- name: Configure Keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
  notify: Restart keepalived

- name: Ensure Keepalived is enabled and running
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true
