---
- name: Install containerd, runc und CNI-Plugins
  hosts: all
  become: true
  vars:
    containerd_version: "2.0.5"
    containerd_release: "containerd-{{ containerd_version }}-linux-amd64"
    containerd_url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/{{ containerd_release }}.tar.gz"
    runc_version: "1.2.6"
    runc_url: "https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.amd64"
    cni_plugins_version: "v1.6.2"
    cni_plugins_release: "cni-plugins-linux-amd64-{{ cni_plugins_version }}"
    cni_plugins_url: "https://github.com/containernetworking/plugins/releases/download/{{ cni_plugins_version }}/{{ cni_plugins_release }}.tgz"

  tasks:
    - name: Download containerd archive
      ansible.builtin.get_url:
        url: "{{ containerd_url }}"
        dest: "/tmp/{{ containerd_release }}.tar.gz"
        mode: "700"

    - name: Extract containerd archive
      ansible.builtin.unarchive:
        src: "/tmp/{{ containerd_release }}.tar.gz"
        dest: "/usr/local/"
        remote_src: true
        creates: "/usr/local/bin/containerd"

    - name: Set containerd binary permissions
      ansible.builtin.file:
        path: "/usr/local/bin/{{ item }}"
        mode: '755'
      loop:
        - containerd
        - containerd-stress
        - containerd-shim-runc-v2
        - ctr

    - name: Download runc binary
      ansible.builtin.get_url:
        url: "{{ runc_url }}"
        dest: "/tmp/runc.amd64"
        mode: '755'

    - name: Install runc
      ansible.builtin.copy:
        src: "/tmp/runc.amd64"
        dest: "/usr/local/sbin/runc"
        remote_src: true
        mode: '0755'

    - name: Download CNI plugins archive
      ansible.builtin.get_url:
        url: "{{ cni_plugins_url }}"
        dest: "/tmp/{{ cni_plugins_release }}.tgz"
        mode: "600"

    - name: Extract CNI plugins
      ansible.builtin.unarchive:
        src: "/tmp/{{ cni_plugins_release }}.tgz"
        dest: "/opt/cni/bin/"
        remote_src: true
        creates: "/opt/cni/bin/bridge"

    - name: Download systemd service for containerd
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service"
        dest: "/usr/lib/systemd/system/containerd.service"
        mode: "0600"

    - name: Reload systemd and enable containerd service
      ansible.builtin.systemd:
        daemon_reload: true
        name: containerd
        enabled: true
        state: started
