- name: Set up Keepalived and HAProxy for high availability
  hosts: kube_control_plane
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - haproxy
          - keepalived
        state: present
        update_cache: true

  roles:
    - keepalived
    - haproxy
