- name: Create kubeadm config
  ansible.builtin.template:
    src: kubeadm-config.yaml.j2
    dest: /root/kubeadm-config.yaml
    mode: "0644"

- name: Initialize kubeadm
  ansible.builtin.command: kubeadm init --control-plane-endpoint "{{ vip_address }}:8443"
  register: init_command
  changed_when: init_command.rc != 0

#- name: Generate and save the join command for the Control Plane node
#  ansible.builtin.command: kubeadm token create --print-join-command
#  register: join_command
#  changed_when: join_command.rc != 0

#- name: Save the join command to join_cp.sh (Control Plane)
#  ansible.builtin.copy:
#    content: "{{ join_command.stdout }}"
#    dest: "/root/join_cp.sh"
#    mode: '0755'
#  when: join_command is defined

#- name: Add control plane join command
#  ansible.builtin.shell: echo " --control-plane" >> /root/join_cp.sh
#  register: cp_init_command
#  changed_when: cp_init_command.rc != 0

#- name: Save the join command to join_worker.sh (Worker)
#  ansible.builtin.copy:
#    content: "{{ join_command.stdout }}"
#    dest: "/root/join_worker.sh"
#    mode: '0755'
#  when: join_command is defined
