---
# Set hostnames for all nodes in the cluster
- name: Change hostnames, so nodes can join the kubeadm cluster
  import_playbook: 01-set-hostnames.yml

# Install basic requirements on all nodes (packages, disable swap, etc.)
- name: Install prerequisites on all nodes
  import_playbook: 01-install-prereqs.yml

# Initialize K3s cluster and install containerd on all nodes
- name: Install containerd on all nodes
  import_playbook: 02-init-k3s-cluster.yml

- name: Install kube-vip on the first control plane node
  import_playbook: 02-init-kube-vip.yml

# Join control plane nodes to the K3s cluster
- name: Configure Keepalived and HAProxy for API server load balancing
  import_playbook: 03-join-k3s-cp.yml

# Join worker nodes to the K3s cluster
- name: Join worker nodes to the K3s cluster
  import_playbook: 03-join-k3s-worker.yml
