- name: Initialize kubeadm on first control plane node
  hosts: "{{ groups['kube_control_plane'][0] }}"
  become: true
  roles:
    - kubeadm

- name: Copy Kubernetes certificates for control plane join
  hosts: "{{ groups['kube_control_plane'][1:] }}, kube_node"
  become: true
  gather_facts: true

  tasks:
    - name: Copy the CA certificate
      ansible.builtin.copy:
        src: "/etc/kubernetes/pki/ca.crt"
        dest: "/etc/kubernetes/pki/ca.crt"
        owner: root
        group: root
        mode: '0644'
        remote_src: true
      delegate_to: "{{ groups['kube_control_plane'][0] }}"

    - name: Copy the service account key
      ansible.builtin.copy:
        src: "/etc/kubernetes/pki/sa.key"
        dest: "/etc/kubernetes/pki/sa.key"
        owner: root
        group: root
        mode: '0600'
        remote_src: true
      delegate_to: "{{ groups['kube_control_plane'][0] }}"

    - name: Copy the front-proxy CA certificate
      ansible.builtin.copy:
        src: "/etc/kubernetes/pki/front-proxy-ca.crt"
        dest: "/etc/kubernetes/pki/front-proxy-ca.crt"
        owner: root
        group: root
        mode: '0644'
        remote_src: true
      delegate_to: "{{ groups['kube_control_plane'][0] }}"

    - name: Copy the etcd CA certificate
      ansible.builtin.copy:
        src: "/etc/kubernetes/pki/etcd/ca.crt"
        dest: "/etc/kubernetes/pki/etcd/ca.crt"
        owner: root
        group: root
        mode: '0644'
        remote_src: true
      delegate_to: "{{ groups['kube_control_plane'][0] }}"
