---
- name: Deploy Longhorn and ArgoCD via Helm
  hosts: "{{ groups['kube_control_plane'][0] }}"
  become: true
  vars:
    argocd_namespace: argocd
    argocd_release_name: argocd
    longhorn_namespace: longhorn-system
    longhorn_release_name: longhorn
    helm_repo_url: https://argoproj.github.io/argo-helm
    helm_chart_name: argo-cd
    repo_url: https://github.com/mainman94/phm.me_cluster.git
    repo_path: /tmp/phm.me_cluster
    helm_home: "{{ lookup('env', 'HELM_HOME') | default('~/.helm', true) }}"
    ansible_python_interpreter: "{{ lookup('pipe', 'which python3') }}"
  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
          - git
        state: present
        update_cache: yes

    - name: Install Helm
      block:
        - name: Download Helm installation script
          get_url:
            url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            dest: /tmp/get-helm-3
            mode: '0755'

        - name: Install Helm
          command: /tmp/get-helm-3
          args:
            creates: /usr/local/bin/helm

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_path }}"
        version: main
        force: yes

    - name: Add Helm repositories
      command: "helm repo add {{ item.name }} {{ item.url }}"
      with_items:
        - { name: 'argo', url: '{{ helm_repo_url }}' }
        - { name: 'longhorn', url: 'https://charts.longhorn.io' }
      args:
        creates: "{{ helm_home }}/repository/{{ item.name }}-index.yaml"

    - name: Update Helm repositories
      command: helm repo update

    - name: Install pipx
      apt:
        name: pipx
        state: present
        update_cache: yes

    - name: Install required Python packages via pipx
      command: "pipx install --include-deps {{ item }}"
      with_items:
        - kubernetes
        - openshift

    - name: Get pipx Python path
      command: pipx environment
      register: pipx_env

    - name: Set Python interpreter
      set_fact:
        ansible_python_interpreter: "{{ pipx_env.stdout | regex_search('PIPX_LOCAL_VENVS=.*') | regex_replace('PIPX_LOCAL_VENVS=(.*)', '\\1/kubernetes/bin/python') }}"

    - name: Create namespaces
      kubernetes.core.k8s:
        name: "{{ item }}"
        api_version: v1
        kind: Namespace
        state: present
      with_items:
        - "{{ longhorn_namespace }}"
        - "{{ argocd_namespace }}"

    - name: Deploy Longhorn via Helm
      kubernetes.core.helm:
        name: "{{ longhorn_release_name }}"
        chart_ref: longhorn
        chart_repo_url: https://charts.longhorn.io
        release_namespace: "{{ longhorn_namespace }}"
        values_files:
          - "{{ repo_path }}/bootstrap/longhorn/values.yaml"

    - name: Wait for Longhorn to be ready
      kubernetes.core.k8s_info:
        kind: Deployment
        name: longhorn-manager
        namespace: "{{ longhorn_namespace }}"
      register: longhorn_status
      until: >
        (longhorn_status.resources is defined and 
        longhorn_status.resources | length > 0 and 
        longhorn_status.resources[0].status.readyReplicas == longhorn_status.resources[0].status.replicas) or
        (longhorn_status.resources is defined and longhorn_status.resources | length == 0)
      retries: 30
      delay: 10

    - name: Deploy ArgoCD via Helm using values from repository
      kubernetes.core.helm:
        name: "{{ argocd_release_name }}"
        chart_ref: "{{ helm_chart_name }}"
        chart_repo_url: "{{ helm_repo_url }}"
        release_namespace: "{{ argocd_namespace }}"
        values_files:
          - "{{ repo_path }}/bootstrap/argocd/values.yaml"
